title: Imagematick                 <script async type="text/javascript">var REPO="Imagematick";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: ImageMagick scripts and snippets for image manipulation
